// Turn your Spotify "Extended streaming history" export into src/data/spotify.ts.
// Usage: node scripts/spotify-history.mjs <folder-with-json-files> [year]
// Request the export at spotify.com/account/privacy (it can take a few weeks).
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const dir = process.argv[2];
const year = Number(process.argv[3] ?? new Date().getFullYear());
if (!dir) {
  console.error("Usage: node scripts/spotify-history.mjs <folder-with-json-files> [year]");
  process.exit(1);
}

const SGT_OFFSET_MS = 8 * 60 * 60 * 1000;
const MIN_PLAY_MS = 30_000;

const files = readdirSync(dir).filter((f) => /Streaming_History_Audio.*\.json$/i.test(f));
if (!files.length) {
  console.error("No Streaming_History_Audio*.json files found in", dir);
  process.exit(1);
}

let totalMs = 0;
const byHourMs = Array(24).fill(0);
const plays = new Map();

for (const f of files) {
  for (const e of JSON.parse(readFileSync(join(dir, f), "utf8"))) {
    if (!e.ts || !e.ms_played) continue;
    const local = new Date(new Date(e.ts).getTime() + SGT_OFFSET_MS);
    if (local.getUTCFullYear() !== year) continue;
    totalMs += e.ms_played;
    byHourMs[local.getUTCHours()] += e.ms_played;
    const name = e.master_metadata_track_name;
    if (name && e.ms_played >= MIN_PLAY_MS) {
      const artist = e.master_metadata_album_artist_name ?? "";
      const key = `${name}\u0000${artist}`;
      const cur = plays.get(key) ?? { name, artist, plays: 0 };
      cur.plays += 1;
      plays.set(key, cur);
    }
  }
}

const top = [...plays.values()].sort((a, b) => b.plays - a.plays)[0] ?? null;
const history = {
  year,
  minutesListened: Math.round(totalMs / 60000),
  mostPlayed: top,
  byHour: byHourMs.map((ms) => Math.round(ms / 60000)),
};

const out = `// Generated by scripts/spotify-history.mjs. Re-run it with a new export to update.
export const spotifyHistory: {
  year: number;
  minutesListened: number | null;
  mostPlayed: { name: string; artist: string; plays: number } | null;
  /** Minutes listened in each hour of the day, index 0 = midnight (Singapore time). */
  byHour: number[] | null;
} = ${JSON.stringify(history, null, 2)};
`;

writeFileSync(new URL("../src/data/spotify.ts", import.meta.url), out);
console.log(`Wrote src/data/spotify.ts: ${history.minutesListened.toLocaleString()} minutes in ${year}.`);
if (top) console.log(`Most played: ${top.name} by ${top.artist} (${top.plays} plays)`);
